plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md
  - inno-alumni-portal_src_api_index_js.md
  - inno-alumni-portal_src_api_sendRequest_js.md
  - inno-alumni-portal_src_api_chart_js.md
